export {default as GoogleIcon} from '../../Assets/Images/Login/google-plus.svg'
export {default as FacebookIcon} from '../../Assets/Images/Login/facebook.svg'
export {default as Password_Eye_Icon_Strike} from '../../Assets/Images/Login/eye-password-see-view.svg'
export {default as Password_Eye_Icon} from '../../Assets/Images/Login/eye-password-show.svg'
export {default as Arrow_right} from '../../Assets/Images/Login/back-arrow.svg'
export {default as Arrow_right_Simple} from '../../Assets/Images/Navigation/chevron-left.svg'
export {default as Exclamatory_Info} from '../../Assets/Images/Register/exclamatory.svg'
export {default as Check_Green} from '../../Assets/Images/Register/success-green-check-mark.svg'
export {default as Arrow_back_color} from '../../Assets/Images/OTP/Arrow_back_Color.svg'
export {default as GamepadTab_Icon} from '../../Assets/Images/Navigation/gamepad.svg'
export {default as AlarmTab_Icon} from '../../Assets/Images/Navigation/alarm.svg'
export {default as ResultTab_Icon} from '../../Assets/Images/Navigation/result.svg'
export {default as UserTab_Icon} from '../../Assets/Images/Navigation/user-icon.svg'
export {default as ShareTab_Icon} from '../../Assets/Images/Navigation/two-male-user.svg'

export {default as GamepadTab_Icon_Gold} from '../../Assets/Images/Navigation/Alternate color icon/gamepad.svg'
export {default as AlarmTab_Icon_Gold} from '../../Assets/Images/Navigation/Alternate color icon/alarm.svg'
export {default as ResultTab_Icon_Gold} from '../../Assets/Images/Navigation/Alternate color icon/result.svg'
export {default as UserTab_Icon_Gold} from '../../Assets/Images/Navigation/Alternate color icon/user-icon.svg'
export {default as ShareTab_Icon_Gold} from '../../Assets/Images/Navigation/Alternate color icon/two-male-user.svg'